applications/about/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'about'
urlpatterns = [
    path('about/', views.about_view, name='about'),

]

applications/contact/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact_view, name= 'contact'),

]

applications/home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),

]

applications/resume/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'resume'
urlpatterns = [
    path('resume/',views.resume_view, name='resume'),
    path('test/',views.TestView.as_view(), name='test'),

]

serviexpo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.sitemaps.views import 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.contact.urls')),
    path('', include('applications.resume.urls')),
    path('', include('applications.project.urls')),
    path('', include('applications.about.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}

<!-- 
<footer class="bg-white py-4 mt-auto">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0">Copyright &copy; RammerBot 2023</div></div>
            <div class="col-auto">
                <a class="small" href="#!">Privacy</a>
                <span class="mx-1">&middot;</span>
                <a class="small" href="#!">Terms</a>
                <span class="mx-1">&middot;</span>
                <a class="small" href="#!">Contact</a>
            </div>
        </div>
    </div>
</footer>
 -->
<footer id="footer" class="bg-color-dark-scale-5 border border-end-0 border-start-0 border-bottom-0 border-color-light-3 mt-0">
    <div class="container text-center my-3 py-5">
        <a href="{% url "home:home" %}" class="goto-top hvr-float-shadow"><img alt="RammerBot" width="120" height="120" data-sticky-width="82" data-sticky-height="36" data-sticky-top="0" src="{% static 'img/logo/logo-rammerbot.png' %}" data-plugin-lazyload data-plugin-options="{'threshold': 500}" data-original="{% static 'img/logo/logo_rammerbot.png' %}"></a>
        <ul class="social-icons social-icons-big social-icons-dark-2">
            <li class="social-icons-instagram"><a href="https://www.instagram.com/rammerbot/" target="_blank" title="Instagram"><i class="fab fa-instagram"></i></a></li>
            <li class="social-icons-facebook"><a href="https://www.facebook.com/RammerBot" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
            <li class="social-icons-twitter"><a href="https://x.com/Rhamer_G" target="_blank" title="Twitter"><i class="fab fa-x"></i></a></li>
            <li class="social-icons-linkedin"><a href="https://www.linkedin.com/in/rammer-gomez/" target="_blank" title="Youtube"><i class="fab fa-linkedin"></i></a></li>
            <li class="social-icons-youtube"><a href="https://github.com/rammerbot" target="_blank" title="Youtube"><i class="fab fa-github"></i></a></li>
        </ul>
    </div>
    <div class="copyright bg-color-dark-scale-4 py-4">
        <div class="container text-center py-2">
            <p class="mb-0 text-2 ls-0">Copyright &copy; RammerBot 2023 - All Rights Reserved</p>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<!-- Navigation-->

<!--
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url "home:home" %}"><span class="fw-bolder hvr-float-shadow text-gradient">RammerBot | ServiExpo</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                <li class="nav-item "><a class="nav-link btn-dark hvr-float-shadow" href="{% url "home:home" %}">Home</a></li>
                <li class="nav-item"><a class="nav-link btn-dark hvr-float-shadow" href="{% url "resume:resume" %}">Resumen</a></li>
                <li class="nav-item"><a class="nav-link btn-dark hvr-float-shadow" href="{% url "project:project" %}">Proyectos</a></li>
                <li class="nav-item"><a class="nav-link btn-dark hvr-float-shadow" href="{% url "contact:contact" %}">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>
-->
<header id="header" class="header header-nav-links header-nav-menu" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': false, 'stickyEnableOnMobile': true, 'stickyStartAt': 70, 'stickyChangeLogo': false, 'stickyHeaderContainerHeight': 70}">
    <div class="header-body border-top-0 bg-black box-shadow-none  ">
        <div class="header-container container h-100">
            <div class="header-row mt-2 h-100">
                <div class="header-column">
                    <div class="header-row pt-4">
                        <div class="header-logo pb-4">
                            <a href="{% url "home:home" %}" class="goto-top hvr-float-shadow"><img alt="RammerBot" width="120" height="120" data-sticky-width="82" data-sticky-height="36" data-sticky-top="0" src="{% static 'img/logo/logo-rammerbot.png' %}" data-plugin-lazyload data-plugin-options="{'threshold': 500}" data-original="{% static 'img/logo/logo_rammerbot.png' %}"></a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-end">
                    <div class="header-row">
                        <button class="btn header-btn-collapse-nav d-lg-none order-3 mt-0 ms-3 me-0" data-bs-toggle="collapse" data-bs-target=".header-nav">
                            <i class="fas fa-bars"></i>
                        </button>
                        <!-- start: header nav menu -->
                        <div class="header-nav header-nav-links header-nav-light-text header-nav-dropdowns-dark collapse">
                            <div class="header-nav-main header-nav-main-mobile-dark header-nav-main-effect-1 header-nav-main-sub-effect-1">
                                <nav>
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li>
                                            <a class="active nav-link hvr-float-shadow" href="{% url "home:home" %}" data-hash data-hash-offset="120">
                                                Inicio
                                            </a>    
                                        </li>
                                        <li class="dropdown">
                                            <a class="nav-link dropdown-toggle hvr-float-shadow" href="{% url "resume:resume" %}">
                                                Resumen
                                            </a>
                                        </li>
                                        <li class="dropdown">
                                            <a class="nav-link dropdown-toggle hvr-float-shadow" href="{% url "project:project" %}">
                                                Proyectos
                                            </a>
                                        </li>
                                        <li class="dropdown">
                                            <a class="nav-link dropdown-toggle hvr-float-shadow" href="{% url "about:about" %}">
                                                Sobre Nosotros
                                            </a>
                                        </li>
                                        <li class="dropdown">
                                            <a class="nav-link dropdown-toggle hvr-float-shadow" href="{% url "contact:contact" %}">
                                                Contactanos
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <!-- end: header nav menu -->
                        <a href="{% url "contact:contact" %} " class="hvr-float-shadow btn btn-gradient btn-modern btn-rounded text-3 ms-4 d-none d-sm-block">!Contactame Ahora!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/includes/javascripts.html
{% load static %}

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<!-- Bootstrap core JS-->
<!-- Core theme JS-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>


<script src="{% static 'vendor/jquery/jquery.js' %}"></script>
		<script src="{% static 'vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
		<script src="{% static 'vendor/popper/umd/popper.min.js' %}"></script>
		<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'vendor/common/common.js' %}"></script>
		<script src="{% static 'vendor/nanoscroller/nanoscroller.js' %}"></script>
		<script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.js' %}"></script>
		<script src="{% static 'vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>

		<!-- Specific Page Vendor -->
		<script src="{% static 'vendor/jquery-appear/jquery.appear.js' %}"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="{% static 'js/theme.js' %}"></script>

		<!-- Theme Custom -->
		<script src="{% static 'js/custom.js' %}"></script>

		<!-- Theme Initialization Files -->
		<script src="{% static 'js/theme.init.js' %}"></script>

		<!-- Specific Page Vendor -->
		<script src="{% static 'vendor/owl.carousel/owl.carousel.js' %}"></script>
		<script src="{% static 'vendor/jquery.lazyload/jquery.lazyload.js' %}"></script>


				<script src="vendor/common/common.js"></script>
				<script src="vendor/nanoscroller/nanoscroller.js"></script>
				<script src="vendor/magnific-popup/jquery.magnific-popup.js"></script>
				<script src="vendor/jquery-placeholder/jquery.placeholder.js"></script>
		
				<!-- Specific Page Vendor -->
				<script src="{% static "vendor/isotope/isotope.js" %}"></script>

				<!-- Examples -->
				<script src="{% static "js/examples/examples.mediagallery.js" %}"></script>